import { FC, ReactNode } from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Header from '@/components/shared/Header';

import Providers from './providers';

import '@/styles/globals.scss';

export const metadata: Metadata = {
    title: 'E-pharmacy',
    description: 'Generated by create next app',
};

const inter = Inter({ subsets: ['latin'], weight: ['400', '500', '600', '700'] });

interface IRootLayout {
    children: ReactNode;
}

const RootLayout: FC<IRootLayout> = ({ children }) => {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Providers>
                    <Header />
                    {children}
                </Providers>
            </body>
        </html>
    );
};

export default RootLayout;
